default:
	just --list

build:
	mvn clean compile

package:
	mvn clean package

run num:
	mvn clean package assembly:single
	java -jar target/COMP535-1.0-SNAPSHOT-jar-with-dependencies.jar conf/router{{num}}.conf

test:
	mvn test
